feat: umbrella rewards configuration (#74)
* feat: umbrella rewards configuration

* feat: add generator

* test: some snapshot tests for umbrella

* docs: update readme

* refactor: importsResolver

* fix: ci

* fix: ci

* chore: misc ci

* chore: fix ci again

* chore: add logger

* chore: revert workflow ci

* chore: new ci flow

* chore: fix ci again

* chore: remove logger

* fix: change method to view

* Update generator/cli.ts

Co-authored-by: Pavel <56404416+pavelvm5@users.noreply.github.com>

---------

Co-authored-by: Pavel <56404416+pavelvm5@users.noreply.github.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,6 +8,33 @@ on:
   workflow_dispatch:
 
 jobs:
-  test:
-    uses: bgd-labs/github-workflows/.github/workflows/foundry-test.yml@main
-    secrets: inherit
+  test-sol:
+    name: Foundry build n test
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - uses: bgd-labs/action-rpc-env@main
+        with:
+          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
+
+      - name: Run Foundry setup
+        uses: bgd-labs/github-workflows/.github/actions/foundry-setup@main
+
+      - name: Run Forge tests
+        id: test
+        uses: bgd-labs/github-workflows/.github/actions/foundry-test@main
+        with:
+          FOUNDRY_PROFILE: "ci"
+
+      - name: Create comment
+        uses: bgd-labs/github-workflows/.github/actions/comment-artifact@main
+
+      # we let failing tests pass so we can log them in the comment, still we want the ci to fail
+      - name: Post test result
+        if: ${{ steps.test.outputs.testStatus != 0 }}
+        run: |
+          echo "tests failed"
+          exit 1
